apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monai-outputs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.outputsSize }}
{{- if .Values.storage.outputsClass }}
  storageClassName: {{ .Values.storage.outputsClass }}
{{- end }}
