apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: monai-frontend
  labels:
    app: monai-frontend
spec:
  to:
    kind: Service
    name: monai-frontend
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
