# Default values for monai-chart.

global:
  suffix: ""

backend:
  replicaCount: 1
  image:
    repository: kishorek123/monai # Update with correct OpenShift ImageStream or registry path
    tag: backend
    pullPolicy: IfNotPresent
  resources:
    limits:
      nvidia.com/gpu: 1
      memory: "8Gi"
      cpu: "4"
    requests:
      nvidia.com/gpu: 1
      memory: "4Gi"
      cpu: "2"
  env:
    ckptPath: /app/outputs/checkpoints/best_cxr_multilabel_13.pt
    valLoaderPath: /app/outputs/val_samples_1.pkl
    tempDir: /app/static/heatmaps

frontend:
  replicaCount: 1
  image:
    repository: kishorek123/monai # Update with correct OpenShift ImageStream or registry path
    tag: frontend
    pullPolicy: IfNotPresent
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "100m"

storage:
  outputsClass: "" # Leave empty for default storage class
  outputsSize: 10Gi
